trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'MTC Denver Sandbox(b0e04a4a-a321-4b66-b8fd-13715262ba3c)'
      subscriptionId: 'b0e04a4a-a321-4b66-b8fd-13715262ba3c'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'demo-mtc-appdev-arm-rg1'
      location: 'West US'
      templateLocation: 'URL of the file'
      csmFileLink: 'https://raw.githubusercontent.com/Lantern-Cloud-Services/demo-mtc-appdev-arm-la/master/template.json'
      csmParametersFileLink: 'https://raw.githubusercontent.com/Lantern-Cloud-Services/demo-mtc-appdev-arm-la/master/parameters.json'
      deploymentMode: 'Incremental'