#Name of the GitHub Action
name: Deploy hello world Logic App

#Set the action on which the workflow will trigger
on:
 workflow_dispatch:
 #push:
 #  tags: 
 #    - v1.0.1
   branches:
     - master
jobs:
  # Composite action
  hello_world_job:
    # Approval gate
    environment:
     name: dev
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: Lantern-Cloud-Services/demo-mtc-appdev-composite-action@v3
        with:
          who-to-greet: 'jdvc the dev'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
  
  
  validate-and-deploy:
   runs-on: ubuntu-latest
   #runs-on: self-hosted
   env:
     ENV_RESOURCEGROUP: demo-mtc-appdev-ghasp-rg1
     ENV_RESOURCEGROUPLOCATION: westus

   steps:

    #Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@master

    #Use the azure provided action to log on to azure using service pricipal
    - name: Login to Azure
      uses: azure/login@v1
      with:
          creds: ${{secrets.AZURE_CREDS}}
    
    # Create the resource group
    - name: Create Resource Group
      run: az group create -n ${{env.ENV_RESOURCEGROUP}} -l ${{env.ENV_RESOURCEGROUPLOCATION}}

    #Validate the  ARM template
    - name: Validate ARM template
      run: |
        az deployment group validate -g ${{env.ENV_RESOURCEGROUP}} --mode Incremental --template-file ./template.json --parameters ./parameters.json
    
    #Deploy the ARM Template
    - name: Deploy Logic App
      run: |
       az group deployment create -g ${{env.ENV_RESOURCEGROUP}} --template-file ./template.json --parameters ./parameters.json
      shell: bash   
      
    # Log Out From Azure 
    - name: Logout
      run: az logout
